kind: Service
apiVersion: v1
metadata:
  name: wordpress
  labels:
    app: wordpress
    app.kubernetes.io/part-of: wordpress-label-group
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: wordpress